sudo: required
language: node_js
node_js:
- 6.10.2
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_8d9defa06872_key -iv $encrypted_8d9defa06872_iv
  -in awesome_rsa.enc -out /tmp/awesome_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/awesome_rsa
- echo "${PASSPHRASE}\n" | ssh-add /tmp/awesome_rsa
- npm install -g release-it
- npm install -g git-release-notes
- chmod +x generate_release_notes.sh
- chmod +x deploy.sh
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "travis-ci"
- git clone --quiet --branch=master git@github.com:dizzy/awesome-project.git > /dev/null
- cd awesome-project
- release-it --non-interactive
- LAST_TAG=$(git tag | sort -r | head -1)
- PREV_TAG=$(git tag | sort -r | head -2 | awk '{split($0, tags, "\n")} END {print tags[1]}')
- git-release-notes ${PREV_TAG}..${LAST_TAG} > changelog-${LAST_TAG}.html
- cd ..
- provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    all_branches: true
after_success: echo "SUCCESS, do something"
