sudo: required
language: node_js
node_js:
- '6.10.2'
env:
  global:
  - secure: Cm4gwZS4r7soQjOVo4OtsPgi9w5iBneZgeDJfdHOl9mnqIy11p207RQKrER2Cv6qVJPy9qAuSrL2gNHJ0kpL064H78z6EJlfIRDkbZu8HE/eaAZ9p8Jpn8BSP+V11ThBcaoTGsR3pW/SA+kvUzK3sfBwnPeHb/NOJXMsV/rNUxQB9yHYLifuj1dLEHh2p2qRScuPudWNv/dcgRZSg5qodqwjUPMf2Jsx0QNm80JKU+BtgO3AHgcOzkwkRQzgSsXhTI0Y/4wZ2eaHeFf6FaGzGkGDDX6wocaCRHynnNY3FtYz7b82RCWiJD3P6C7jz7lCPxwEdKS2KMO+94GPvHWTNfJZAT2UlH8AP5Ag0rDiBAjYPocO+HUBlbksRInhGjNankSFssOcmvsmJk4jZhJpOm4FaORflh9rTkvRUawIH3TrLdXcmbY73grpBMFdGZ1tbrwv6w7NGqou+21e9QIyX3ouXAz7u48OPYhWTZD1VE0S+JYyphCnXo5cNY51ETcvnzDfkguLB0281SrzRU3FK9v5QNFJQd3Cj5BDmCaJjpc1E1CsilMvKrR32uCae9imZeW9AtNHu+wQyeXxXcuCp4ifGZwFWayTjBwCFeHmcNxVgeOaBJ7A/7ut2TvsorfJd2N6fZHnCAXG+tqG2Yiu4zvffxL92ElvTfmaA6WreyY=
branches:
  only:
  - master
before_install:
  - npm install -g release-it
  - npm install -g git-release-notes
  - chmod +x generate_release_notes.sh
  - chmod +x deploy.sh
  - git clone --quiet --branch=master https://${GH_TOKEN}@github.com/dizzy/awesome-project > /dev/null
install:
  - cd awesome-project
  - release-it -g --non-interactive
  - cd ..
deploy:
- provider: script
  skip_cleanup: true
  script: ./generate_release_notes.sh
  on:
    all_branches: true
- provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    all_branches: true
after_success:
  echo "SUCCESS, do something"
